### ISSUE TITLE
WSAmateur doesn't start on Linux

### ISSUE THREAD

**Issue by olegshtch** [longagofaraway/WSAmateur#5]
I'm trying to play it on Linux and get error at start:

```
QQmlComponent: Component is not ready
qrc:/qml/StartWindow.qml:75: TypeError: Cannot read property 'anchors' of null
```

UI shows Loading and nothing else.

**Comment by longagofaraway** [comment]
Just tried it on Ubuntu 18.04, Qt 5.15.2. It's working. What commit were you building? What's your Qt version, Linux distro?

**Comment by olegshtch** [comment]
Devuan testing (daedalus - Debian's Bookworm), Qt 5.15.2. Maybe it's paths issue?

**Comment by longagofaraway** [comment]
`QQmlComponent: Component is not ready`
This error usually means that a Qml object is being created dynamically, but Qml code in that object contains an error. To see the real error I usually create the problematic object statically.

`qrc:/qml/StartWindow.qml:75: TypeError: Cannot read property 'anchors' of null`
If you didn't have any data in .local/share/WSAmateur, the problem is in 'menu/ChooseFileWindow.qml', since it starts first. Could you please create that object statically in the 'StartWindow.qml' and see the error?

**Comment by olegshtch** [comment]
I'm not sure how to do it in QML.

**Comment by longagofaraway** [comment]
In StartWindow.qml file add:
```
Item {
    id: startWindow
    ...

    // add this
    ChooseFileWindow {
        anchors.centerIn: startWindow
    }

    ...
}
```
And see what happens.

**Comment by olegshtch** [comment]
I got: 

```
qrc:/qml/StartWindow.qml:26:5: Type ChooseFileWindow unavailable
qrc:/qml/menu/ChooseFileWindow.qml:2:1: module "QtQuick.Dialogs" is not installed
```

Fixed with `qml-module-qtquick-dialogs` installed.
